# - name: Install Nginx
#   ansible.builtin.dnf:
#       name: nginx
#       state: installed

# - name: Remove nginx default content
#   ansible.builtin.file: 
#       path: /usr/share/nginx/html
#       state: absent  

- name: find files
  ansible.builtin.find:
      paths: /etc/systemd
      file_type: file
  register: out

- name: Printing files
  ansible.builtin.shell: echo ' files = "{{ item.path }}"'
  loop: "{{ out.files }}"


