- name: Install Mysql
  ansible.builtin.dnf:
      name: Mysql
      state: present 
- name: To start Mysql
  ansible.builtin.systemd_service:
      name: mysqld
      state: started
      enable: true
- name: To root mysql password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass ExpenseApp@1