- name: To download prometheus content
  ansible.builtin.unarchive: 
      src: https://github.com/prometheus/prometheus/releases/download/v2.50.1/prometheus-2.50.1.linux-amd64.tar.gz
      dest: /opt 
      remote_src: yes

- name: To prometheus service file
  ansible.builtin.template: 
      src: prometheus.service
      dest: /etc//systemd/system/prometheus.service

- name: copy prometheus configuration file
  ansible.builtin.template:
      src: prometheusold.yml
      dest: /opt/prometheus-2.50.1.linux-amd64/prometheusold.yml
  tags: copyfile         

- name: To start prometheus
  ansible.builtin.systemd_service:
      name: prometheus
      state: restarted
      daemon_reload: yes
      enabled: yes
  tags: copyfile